name: ci/cd-pipeline

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy to docker
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: deploy to docker
      - uses: actions/checkout@v2
        run: |
          docker-compose up --force-recreate --build --detach
          docker image prune -a -f