name: ci/cd-pipeline

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy to docker
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.0
      with:
        compose-file: "./docker-compose.yml"