name: ci/cd-pipeline

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: deploy to vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }
          key: ${{ secrets.VPS_SSH_KEY }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: 22
          script: |
            cd ${{ secretes.PROJECT_PATH }}
            git pull origin main
            docker-compose up --force-recreate --build --detach
            docker image prune -a -f